# Generated by Django 4.2.7 on 2023-12-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='current_workplace',
        ),
        migrations.AddField(
            model_name='profile',
            name='field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.IntegerField(choices=[(0, 'Unemployed'), (1, 'Intern'), (2, 'Employed')], default=0),
        ),
    ]
