# Generated by Django 4.2.7 on 2023-12-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
