# Generated by Django 4.2.7 on 2023-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_education_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_name',
            field=models.CharField(max_length=100),
        ),
    ]
